package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author glaucio
 */
public class FrmConection extends javax.swing.JFrame {

  /**
   * Creates new form FrmConection
   */
  public FrmConection() {
    initComponents();
    loadConfig();
  }

  private void loadConfig() {
    try {
      FrmMain.CONFIG.lerConfig();

      jrbBasexServer.setSelected(false);
      jrbSaxon.setSelected(false);

      String t = FrmMain.CONFIG.getTypeOfConection();
      if (t.equals("b")) {
        jrbBasexServer.setSelected(true);
      } else if (t.equals("s")) {
        jrbSaxon.setSelected(true);
      }

      tfUser.setText(FrmMain.CONFIG.getUser());
      tfPassword.setText(FrmMain.CONFIG.getPassword());
      tfHost.setText(FrmMain.CONFIG.getHost());
      tfPorta.setText(FrmMain.CONFIG.getPort());
    } catch (Exception ex) {
      Logger.getLogger(FrmConection.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, ex.getMessage());
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    btOK = new javax.swing.JButton();
    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    lbSaxon1 = new javax.swing.JLabel();
    lbSaxon2 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    lbUsuario = new javax.swing.JLabel();
    tfUser = new javax.swing.JTextField();
    lbSenha = new javax.swing.JLabel();
    tfHost = new javax.swing.JTextField();
    tfPassword = new javax.swing.JPasswordField();
    lbHost = new javax.swing.JLabel();
    lbPorta = new javax.swing.JLabel();
    tfPorta = new javax.swing.JTextField();
    jPanel3 = new javax.swing.JPanel();
    jrbSaxon = new javax.swing.JRadioButton();
    jrbBasexServer = new javax.swing.JRadioButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("view/Bundle", FrmMain.local); // NOI18N
    setTitle(bundle.getString("FrmConection.title")); // NOI18N
    setResizable(false);

    btOK.setText(bundle.getString("FrmConection.btOK.text")); // NOI18N
    btOK.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btOKActionPerformed(evt);
      }
    });

    lbSaxon1.setText(bundle.getString("FrmConection.lbSaxon1.text")); // NOI18N

    lbSaxon2.setText(bundle.getString("FrmConection.lbSaxon2.text")); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lbSaxon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(lbSaxon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addContainerGap()))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(56, 56, 56)
        .addComponent(lbSaxon1)
        .addContainerGap(129, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addGap(92, 92, 92)
          .addComponent(lbSaxon2)
          .addContainerGap(93, Short.MAX_VALUE)))
    );

    jTabbedPane1.addTab(bundle.getString("FrmConection.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

    lbUsuario.setText(bundle.getString("FrmConection.lbUsuario.text")); // NOI18N

    lbSenha.setText(bundle.getString("FrmConection.lbSenha.text")); // NOI18N
    
    lbHost.setText(bundle.getString("FrmConection.lbHost.text")); // NOI18N

    lbPorta.setText(bundle.getString("FrmConection.lbPorta.text")); // NOI18N

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(lbUsuario)
            .addGap(18, 18, 18)
            .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(lbPorta)
            .addGap(18, 18, 18)
            .addComponent(tfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(lbHost)
            .addGap(18, 18, 18)
            .addComponent(tfHost, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(lbSenha)
            .addGap(18, 18, 18)
            .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(89, Short.MAX_VALUE))
    );

    jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbHost, lbPorta, lbSenha, lbUsuario});

    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbUsuario)
          .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(23, 23, 23)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbSenha)
          .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbHost)
          .addComponent(tfHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbPorta)
          .addComponent(tfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab(bundle.getString("FrmConection.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

    buttonGroup1.add(jrbSaxon);
    jrbSaxon.setText(bundle.getString("FrmConection.jrbSaxon.text")); // NOI18N

    buttonGroup1.add(jrbBasexServer);
    jrbBasexServer.setText(bundle.getString("FrmConection.jrbBasexServer.text")); // NOI18N

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jrbSaxon)
          .addComponent(jrbBasexServer))
        .addContainerGap(312, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jrbSaxon)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jrbBasexServer)
        .addContainerGap(140, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab(bundle.getString("FrmConection.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btOK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btOK)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTabbedPane1.getAccessibleContext().setAccessibleName(bundle.getString("FrmConection.jTabbedPane1.AccessibleContext.accessibleName")); // NOI18N

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
    FrmMain.CONFIG.setHost(tfHost.getText());
    FrmMain.CONFIG.setPassword(tfPassword.getText());
    FrmMain.CONFIG.setPort(tfPorta.getText());
    FrmMain.CONFIG.setUser(tfUser.getText());

    if (jrbBasexServer.isSelected()) {
      FrmMain.CONFIG.setTypeOfConection("b");
    } else if (jrbSaxon.isSelected()) {
      FrmMain.CONFIG.setTypeOfConection("s");
    }
    try {
      FrmMain.CONFIG.salvarConfig();
    } catch (Exception ex) {
      Logger.getLogger(FrmConection.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, ex.getMessage());
    }

    setVisible(false);
  }//GEN-LAST:event_btOKActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btOK;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JRadioButton jrbBasexServer;
  private javax.swing.JRadioButton jrbSaxon;
  private javax.swing.JLabel lbHost;
  private javax.swing.JLabel lbPorta;
  private javax.swing.JLabel lbSaxon1;
  private javax.swing.JLabel lbSaxon2;
  private javax.swing.JLabel lbSenha;
  private javax.swing.JLabel lbUsuario;
  private javax.swing.JTextField tfHost;
  private javax.swing.JPasswordField tfPassword;
  private javax.swing.JTextField tfPorta;
  private javax.swing.JTextField tfUser;
  // End of variables declaration//GEN-END:variables
}
